name: DDI PDF Snapshot to Maven Central Repository
on:
    push:
        branches:
            - main
        paths:
            - "ddi-pdf/**"
    pull_request:
        branches:
            - main
        paths:
            - "ddi-pdf/**"
jobs:
    publish:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, '[maven-release-plugin]') }}
        strategy:
            matrix:
                java: [17]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v4
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'adopt'
                  server-id: ossrh
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Build, test, verify and publish snapshot
              run: mvn -f ddi-pdf -B verify -Djdk.version=${{ matrix.java }}
            - name: Publish snapshot
              if: ${{ matrix.java == '17' }}
              run: mvn -f ddi-pdf deploy -DskipAnalysis -DskipUT -DskipIT -Djdk.version=${{ matrix.java }}
              env:
                  MAVEN_USERNAME: ${{ secrets.DATAVERSEBOT_SONATYPE_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.DATAVERSEBOT_SONATYPE_TOKEN }}
